"""USMSB Platform Extensions Module."""

from usmsb_sdk.platform.blockchain.adapter import (
    IBlockchainAdapter,
    EthereumAdapter,
    MockBlockchainAdapter,
    BlockchainNetwork,
    Transaction,
    TransactionStatus,
    WalletInfo,
    SmartContract,
)
from usmsb_sdk.platform.blockchain.digital_currency_manager import (
    DigitalCurrencyManager,
    CurrencyConfig,
    CurrencyBalance,
    CurrencyTransaction,
    CurrencyType,
    TransactionType,
)
from usmsb_sdk.platform.protocols.mcp_adapter import (
    MCPAdapter,
    MCPConnection,
    MCPResource,
    MCPResourceType,
    MCPTool,
    MCPToolResult,
    MCPToolStatus,
    MCPPrompt,
    MCPSamplingRequest,
    MCPSamplingResponse,
    MCPMessageType,
    create_standard_tools,
)
from usmsb_sdk.platform.external.external_agent_adapter import (
    ExternalAgentAdapter,
    ExternalAgentProfile,
    ExternalAgentProtocol,
    ExternalAgentStatus,
    ExternalAgentCall,
    ExternalAgentResponse,
    SkillDefinition,
    SkillMatchLevel,
    ProtocolHandler,
    A2AProtocolHandler,
    HTTPProtocolHandler,
    create_skill_from_dict,
    create_agent_from_skill_md,
)
from usmsb_sdk.platform.environment.broadcast_service import (
    EnvironmentBroadcastService,
    BroadcastMessage,
    BroadcastType,
    BroadcastPriority,
    BroadcastScope,
    Subscription,
    BroadcastStats,
)

__all__ = [
    # Blockchain
    "IBlockchainAdapter",
    "EthereumAdapter",
    "MockBlockchainAdapter",
    "BlockchainNetwork",
    "Transaction",
    "TransactionStatus",
    "WalletInfo",
    "SmartContract",
    # Digital Currency
    "DigitalCurrencyManager",
    "CurrencyConfig",
    "CurrencyBalance",
    "CurrencyTransaction",
    "CurrencyType",
    "TransactionType",
    # MCP Protocol
    "MCPAdapter",
    "MCPConnection",
    "MCPResource",
    "MCPResourceType",
    "MCPTool",
    "MCPToolResult",
    "MCPToolStatus",
    "MCPPrompt",
    "MCPSamplingRequest",
    "MCPSamplingResponse",
    "MCPMessageType",
    "create_standard_tools",
    # External Agent
    "ExternalAgentAdapter",
    "ExternalAgentProfile",
    "ExternalAgentProtocol",
    "ExternalAgentStatus",
    "ExternalAgentCall",
    "ExternalAgentResponse",
    "SkillDefinition",
    "SkillMatchLevel",
    "ProtocolHandler",
    "A2AProtocolHandler",
    "HTTPProtocolHandler",
    "create_skill_from_dict",
    "create_agent_from_skill_md",
    # Environment Broadcast
    "EnvironmentBroadcastService",
    "BroadcastMessage",
    "BroadcastType",
    "BroadcastPriority",
    "BroadcastScope",
    "Subscription",
    "BroadcastStats",
]
