"""Export the audited SDK subset; never rewrite its source.

Core/autonomy needs stdlib only. The optional learning adapter reuses existing
Harness contracts and requires Pydantic 2; no model, provider or chain SDK.

Usage: python scripts/export_autonomy.py <destination-package> [--check]
The package has namespace shims because the full SDK has eager optional imports.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
FILES = {"core/elements.py": "src/usmsb_sdk/core/elements.py",
         "autonomy/__init__.py": "src/usmsb_sdk/autonomy/__init__.py",
         "autonomy/contracts.py": "src/usmsb_sdk/autonomy/contracts.py",
         "autonomy/evolution.py": "src/usmsb_sdk/autonomy/evolution.py",
         "autonomy/authorization.py": "src/usmsb_sdk/autonomy/authorization.py",
         "autonomy/learning.py": "src/usmsb_sdk/autonomy/learning.py",
         "autonomy/collaboration.py": "src/usmsb_sdk/autonomy/collaboration.py",
         "growth_economic_harness/models.py": "src/usmsb_sdk/growth_economic_harness/models.py",
         "growth_economic_harness/experience_loop.py": "src/usmsb_sdk/growth_economic_harness/experience_loop.py",
         "autonomy/world_model.py": "src/usmsb_sdk/autonomy/world_model.py",
         "autonomy/open_world.py": "src/usmsb_sdk/autonomy/open_world.py", "LICENSE": "LICENSE"}


def export(destination, check=False):
    destination = Path(destination)
    content = {target: (ROOT / source).read_bytes().replace(b"\r\n", b"\n") for target, source in FILES.items()}
    content.update({name: b'"""Portable USMSB namespace; generated by scripts/export_autonomy.py."""\n'
                    for name in ("__init__.py", "core/__init__.py", "growth_economic_harness/__init__.py")})
    revision = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    source_status = subprocess.check_output(
        ["git", "status", "--porcelain", "--", *FILES.values()], cwd=ROOT, text=True).splitlines()
    source_hashes = {p: hashlib.sha256(b).hexdigest() for p, b in content.items()}
    manifest = {"upstream": "https://github.com/usmsb/usmsb", "revision": revision,
                "revision_kind": "base_commit_with_worktree_changes" if source_status else "commit",
                "source_status": source_status,
                "content_digest": hashlib.sha256(json.dumps(source_hashes, sort_keys=True).encode()).hexdigest(),
                "source_paths": FILES,
                "sha256": source_hashes}
    content["MANIFEST.json"] = (json.dumps(manifest, indent=2) + "\n").encode()
    for name, data in content.items():
        path = destination / name
        if check:
            if not path.is_file() or path.read_bytes() != data:
                raise ValueError(f"Portable SDK drift: {name}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    return manifest


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("destination")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    print(json.dumps(export(args.destination, args.check), indent=2))
