/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AssetVault {
  export type AssetInfoStruct = {
    assetId: BytesLike;
    nftContract: AddressLike;
    nftTokenId: BigNumberish;
    originalOwner: AddressLike;
    totalShares: BigNumberish;
    sharePrice: BigNumberish;
    sharesSold: BigNumberish;
    totalEarnings: BigNumberish;
    distributedEarnings: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
  };

  export type AssetInfoStructOutput = [
    assetId: string,
    nftContract: string,
    nftTokenId: bigint,
    originalOwner: string,
    totalShares: bigint,
    sharePrice: bigint,
    sharesSold: bigint,
    totalEarnings: bigint,
    distributedEarnings: bigint,
    status: bigint,
    createdAt: bigint
  ] & {
    assetId: string;
    nftContract: string;
    nftTokenId: bigint;
    originalOwner: string;
    totalShares: bigint;
    sharePrice: bigint;
    sharesSold: bigint;
    totalEarnings: bigint;
    distributedEarnings: bigint;
    status: bigint;
    createdAt: bigint;
  };

  export type ShareholderStruct = {
    shares: BigNumberish;
    claimedEarnings: BigNumberish;
    purchaseTime: BigNumberish;
  };

  export type ShareholderStructOutput = [
    shares: bigint,
    claimedEarnings: bigint,
    purchaseTime: bigint
  ] & { shares: bigint; claimedEarnings: bigint; purchaseTime: bigint };
}

export interface AssetVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CREATOR_SHARE_BPS"
      | "MAX_SHARES"
      | "MIN_SHARES"
      | "PLATFORM_FEE_BPS"
      | "allAssets"
      | "assetHolders"
      | "assets"
      | "claimEarnings"
      | "depositAndFragment"
      | "distributeEarnings"
      | "getAsset"
      | "getAssetCount"
      | "getAssetHolders"
      | "getShareholder"
      | "getStats"
      | "getUnclaimedEarnings"
      | "getUserAssets"
      | "isHolder"
      | "lockAsset"
      | "owner"
      | "pause"
      | "paused"
      | "paymentToken"
      | "purchaseShares"
      | "redeemNFT"
      | "renounceOwnership"
      | "setPaymentToken"
      | "shareholders"
      | "totalAssetsFragmented"
      | "totalVolume"
      | "transferOwnership"
      | "transferShares"
      | "unlockAsset"
      | "unpause"
      | "userAssets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetFragmented"
      | "AssetLocked"
      | "AssetUnlocked"
      | "EarningsClaimed"
      | "EarningsDistributed"
      | "NFTRedeemed"
      | "OwnershipTransferred"
      | "Paused"
      | "SharesPurchased"
      | "SharesTransferred"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CREATOR_SHARE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SHARES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_SHARES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allAssets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assetHolders",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "assets", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "claimEarnings",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositAndFragment",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeEarnings",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getAsset", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAssetCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetHolders",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getShareholder",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getUnclaimedEarnings",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAssets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isHolder",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockAsset",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseShares",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemNFT",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shareholders",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAssetsFragmented",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferShares",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockAsset",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userAssets",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CREATOR_SHARE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_SHARES", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_SHARES", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allAssets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetHolders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositAndFragment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAssetCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetHolders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShareholder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUnclaimedEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isHolder", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockAsset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeemNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shareholders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAssetsFragmented",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userAssets", data: BytesLike): Result;
}

export namespace AssetFragmentedEvent {
  export type InputTuple = [
    assetId: BytesLike,
    nftContract: AddressLike,
    tokenId: BigNumberish,
    totalShares: BigNumberish,
    sharePrice: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    nftContract: string,
    tokenId: bigint,
    totalShares: bigint,
    sharePrice: bigint
  ];
  export interface OutputObject {
    assetId: string;
    nftContract: string;
    tokenId: bigint;
    totalShares: bigint;
    sharePrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetLockedEvent {
  export type InputTuple = [assetId: BytesLike, reason: string];
  export type OutputTuple = [assetId: string, reason: string];
  export interface OutputObject {
    assetId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetUnlockedEvent {
  export type InputTuple = [assetId: BytesLike];
  export type OutputTuple = [assetId: string];
  export interface OutputObject {
    assetId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EarningsClaimedEvent {
  export type InputTuple = [
    assetId: BytesLike,
    holder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [assetId: string, holder: string, amount: bigint];
  export interface OutputObject {
    assetId: string;
    holder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EarningsDistributedEvent {
  export type InputTuple = [
    assetId: BytesLike,
    amount: BigNumberish,
    perShare: BigNumberish
  ];
  export type OutputTuple = [assetId: string, amount: bigint, perShare: bigint];
  export interface OutputObject {
    assetId: string;
    amount: bigint;
    perShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTRedeemedEvent {
  export type InputTuple = [
    assetId: BytesLike,
    redeemer: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    redeemer: string,
    tokenId: bigint
  ];
  export interface OutputObject {
    assetId: string;
    redeemer: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesPurchasedEvent {
  export type InputTuple = [
    assetId: BytesLike,
    buyer: AddressLike,
    shareAmount: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    buyer: string,
    shareAmount: bigint,
    price: bigint
  ];
  export interface OutputObject {
    assetId: string;
    buyer: string;
    shareAmount: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesTransferredEvent {
  export type InputTuple = [
    assetId: BytesLike,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    assetId: string,
    from: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    assetId: string;
    from: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AssetVault extends BaseContract {
  connect(runner?: ContractRunner | null): AssetVault;
  waitForDeployment(): Promise<this>;

  interface: AssetVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CREATOR_SHARE_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_SHARES: TypedContractMethod<[], [bigint], "view">;

  MIN_SHARES: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  allAssets: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  assetHolders: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  assets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        assetId: string;
        nftContract: string;
        nftTokenId: bigint;
        originalOwner: string;
        totalShares: bigint;
        sharePrice: bigint;
        sharesSold: bigint;
        totalEarnings: bigint;
        distributedEarnings: bigint;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  claimEarnings: TypedContractMethod<
    [assetId: BytesLike],
    [void],
    "nonpayable"
  >;

  depositAndFragment: TypedContractMethod<
    [
      nftContract: AddressLike,
      tokenId: BigNumberish,
      totalShares: BigNumberish,
      sharePrice: BigNumberish,
      metadata: string
    ],
    [string],
    "nonpayable"
  >;

  distributeEarnings: TypedContractMethod<
    [assetId: BytesLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  getAsset: TypedContractMethod<
    [assetId: BytesLike],
    [AssetVault.AssetInfoStructOutput],
    "view"
  >;

  getAssetCount: TypedContractMethod<[], [bigint], "view">;

  getAssetHolders: TypedContractMethod<
    [assetId: BytesLike],
    [string[]],
    "view"
  >;

  getShareholder: TypedContractMethod<
    [assetId: BytesLike, holder: AddressLike],
    [AssetVault.ShareholderStructOutput],
    "view"
  >;

  getStats: TypedContractMethod<[], [[bigint, bigint, bigint]], "view">;

  getUnclaimedEarnings: TypedContractMethod<
    [assetId: BytesLike, holder: AddressLike],
    [bigint],
    "view"
  >;

  getUserAssets: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  isHolder: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  lockAsset: TypedContractMethod<
    [assetId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  purchaseShares: TypedContractMethod<
    [assetId: BytesLike, shareAmount: BigNumberish],
    [void],
    "payable"
  >;

  redeemNFT: TypedContractMethod<[assetId: BytesLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPaymentToken: TypedContractMethod<
    [_paymentToken: AddressLike],
    [void],
    "nonpayable"
  >;

  shareholders: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint] & {
        shares: bigint;
        claimedEarnings: bigint;
        purchaseTime: bigint;
      }
    ],
    "view"
  >;

  totalAssetsFragmented: TypedContractMethod<[], [bigint], "view">;

  totalVolume: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferShares: TypedContractMethod<
    [assetId: BytesLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unlockAsset: TypedContractMethod<[assetId: BytesLike], [void], "nonpayable">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userAssets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CREATOR_SHARE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SHARES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_SHARES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allAssets"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "assetHolders"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "assets"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        assetId: string;
        nftContract: string;
        nftTokenId: bigint;
        originalOwner: string;
        totalShares: bigint;
        sharePrice: bigint;
        sharesSold: bigint;
        totalEarnings: bigint;
        distributedEarnings: bigint;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimEarnings"
  ): TypedContractMethod<[assetId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositAndFragment"
  ): TypedContractMethod<
    [
      nftContract: AddressLike,
      tokenId: BigNumberish,
      totalShares: BigNumberish,
      sharePrice: BigNumberish,
      metadata: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeEarnings"
  ): TypedContractMethod<
    [assetId: BytesLike, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getAsset"
  ): TypedContractMethod<
    [assetId: BytesLike],
    [AssetVault.AssetInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAssetCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAssetHolders"
  ): TypedContractMethod<[assetId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getShareholder"
  ): TypedContractMethod<
    [assetId: BytesLike, holder: AddressLike],
    [AssetVault.ShareholderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<[], [[bigint, bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "getUnclaimedEarnings"
  ): TypedContractMethod<
    [assetId: BytesLike, holder: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserAssets"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isHolder"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockAsset"
  ): TypedContractMethod<
    [assetId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseShares"
  ): TypedContractMethod<
    [assetId: BytesLike, shareAmount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "redeemNFT"
  ): TypedContractMethod<[assetId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaymentToken"
  ): TypedContractMethod<[_paymentToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "shareholders"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint] & {
        shares: bigint;
        claimedEarnings: bigint;
        purchaseTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalAssetsFragmented"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferShares"
  ): TypedContractMethod<
    [assetId: BytesLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unlockAsset"
  ): TypedContractMethod<[assetId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userAssets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "AssetFragmented"
  ): TypedContractEvent<
    AssetFragmentedEvent.InputTuple,
    AssetFragmentedEvent.OutputTuple,
    AssetFragmentedEvent.OutputObject
  >;
  getEvent(
    key: "AssetLocked"
  ): TypedContractEvent<
    AssetLockedEvent.InputTuple,
    AssetLockedEvent.OutputTuple,
    AssetLockedEvent.OutputObject
  >;
  getEvent(
    key: "AssetUnlocked"
  ): TypedContractEvent<
    AssetUnlockedEvent.InputTuple,
    AssetUnlockedEvent.OutputTuple,
    AssetUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "EarningsClaimed"
  ): TypedContractEvent<
    EarningsClaimedEvent.InputTuple,
    EarningsClaimedEvent.OutputTuple,
    EarningsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "EarningsDistributed"
  ): TypedContractEvent<
    EarningsDistributedEvent.InputTuple,
    EarningsDistributedEvent.OutputTuple,
    EarningsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "NFTRedeemed"
  ): TypedContractEvent<
    NFTRedeemedEvent.InputTuple,
    NFTRedeemedEvent.OutputTuple,
    NFTRedeemedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "SharesPurchased"
  ): TypedContractEvent<
    SharesPurchasedEvent.InputTuple,
    SharesPurchasedEvent.OutputTuple,
    SharesPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "SharesTransferred"
  ): TypedContractEvent<
    SharesTransferredEvent.InputTuple,
    SharesTransferredEvent.OutputTuple,
    SharesTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AssetFragmented(bytes32,address,uint256,uint256,uint256)": TypedContractEvent<
      AssetFragmentedEvent.InputTuple,
      AssetFragmentedEvent.OutputTuple,
      AssetFragmentedEvent.OutputObject
    >;
    AssetFragmented: TypedContractEvent<
      AssetFragmentedEvent.InputTuple,
      AssetFragmentedEvent.OutputTuple,
      AssetFragmentedEvent.OutputObject
    >;

    "AssetLocked(bytes32,string)": TypedContractEvent<
      AssetLockedEvent.InputTuple,
      AssetLockedEvent.OutputTuple,
      AssetLockedEvent.OutputObject
    >;
    AssetLocked: TypedContractEvent<
      AssetLockedEvent.InputTuple,
      AssetLockedEvent.OutputTuple,
      AssetLockedEvent.OutputObject
    >;

    "AssetUnlocked(bytes32)": TypedContractEvent<
      AssetUnlockedEvent.InputTuple,
      AssetUnlockedEvent.OutputTuple,
      AssetUnlockedEvent.OutputObject
    >;
    AssetUnlocked: TypedContractEvent<
      AssetUnlockedEvent.InputTuple,
      AssetUnlockedEvent.OutputTuple,
      AssetUnlockedEvent.OutputObject
    >;

    "EarningsClaimed(bytes32,address,uint256)": TypedContractEvent<
      EarningsClaimedEvent.InputTuple,
      EarningsClaimedEvent.OutputTuple,
      EarningsClaimedEvent.OutputObject
    >;
    EarningsClaimed: TypedContractEvent<
      EarningsClaimedEvent.InputTuple,
      EarningsClaimedEvent.OutputTuple,
      EarningsClaimedEvent.OutputObject
    >;

    "EarningsDistributed(bytes32,uint256,uint256)": TypedContractEvent<
      EarningsDistributedEvent.InputTuple,
      EarningsDistributedEvent.OutputTuple,
      EarningsDistributedEvent.OutputObject
    >;
    EarningsDistributed: TypedContractEvent<
      EarningsDistributedEvent.InputTuple,
      EarningsDistributedEvent.OutputTuple,
      EarningsDistributedEvent.OutputObject
    >;

    "NFTRedeemed(bytes32,address,uint256)": TypedContractEvent<
      NFTRedeemedEvent.InputTuple,
      NFTRedeemedEvent.OutputTuple,
      NFTRedeemedEvent.OutputObject
    >;
    NFTRedeemed: TypedContractEvent<
      NFTRedeemedEvent.InputTuple,
      NFTRedeemedEvent.OutputTuple,
      NFTRedeemedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "SharesPurchased(bytes32,address,uint256,uint256)": TypedContractEvent<
      SharesPurchasedEvent.InputTuple,
      SharesPurchasedEvent.OutputTuple,
      SharesPurchasedEvent.OutputObject
    >;
    SharesPurchased: TypedContractEvent<
      SharesPurchasedEvent.InputTuple,
      SharesPurchasedEvent.OutputTuple,
      SharesPurchasedEvent.OutputObject
    >;

    "SharesTransferred(bytes32,address,address,uint256)": TypedContractEvent<
      SharesTransferredEvent.InputTuple,
      SharesTransferredEvent.OutputTuple,
      SharesTransferredEvent.OutputObject
    >;
    SharesTransferred: TypedContractEvent<
      SharesTransferredEvent.InputTuple,
      SharesTransferredEvent.OutputTuple,
      SharesTransferredEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
