/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace VIBStaking {
  export type StakeInfoStruct = {
    amount: BigNumberish;
    tier: BigNumberish;
    lockPeriod: BigNumberish;
    stakeTime: BigNumberish;
    unlockTime: BigNumberish;
    rewardPerTokenPaid: BigNumberish;
    isActive: boolean;
  };

  export type StakeInfoStructOutput = [
    amount: bigint,
    tier: bigint,
    lockPeriod: bigint,
    stakeTime: bigint,
    unlockTime: bigint,
    rewardPerTokenPaid: bigint,
    isActive: boolean
  ] & {
    amount: bigint;
    tier: bigint;
    lockPeriod: bigint;
    stakeTime: bigint;
    unlockTime: bigint;
    rewardPerTokenPaid: bigint;
    isActive: boolean;
  };
}

export interface VIBStakingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LOCK_BONUS_180_DAYS"
      | "LOCK_BONUS_30_DAYS"
      | "LOCK_BONUS_365_DAYS"
      | "LOCK_BONUS_90_DAYS"
      | "LOCK_BONUS_NONE"
      | "LOCK_PERIOD_180_DAYS"
      | "LOCK_PERIOD_30_DAYS"
      | "LOCK_PERIOD_365_DAYS"
      | "LOCK_PERIOD_90_DAYS"
      | "LOCK_PERIOD_NONE"
      | "MAX_APY"
      | "MIN_APY"
      | "REWARD_PRECISION"
      | "SECONDS_PER_YEAR"
      | "TIER_MIN_BRONZE"
      | "TIER_MIN_GOLD"
      | "TIER_MIN_PLATINUM"
      | "TIER_MIN_SILVER"
      | "addRewards"
      | "calculateTier"
      | "claimReward"
      | "currentAPY"
      | "emergencyWithdraw"
      | "getPendingReward"
      | "getStakeInfo"
      | "getStakerCount"
      | "getStakers"
      | "getUserTier"
      | "isStaker"
      | "lastUpdateTime"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "rewardPerTokenStored"
      | "rewards"
      | "setAPY"
      | "setVibeToken"
      | "stake"
      | "stakeInfos"
      | "stakers"
      | "totalRewardsDistributed"
      | "totalStaked"
      | "transferOwnership"
      | "unpause"
      | "unstake"
      | "updateGlobalRewards"
      | "vibeToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "APYUpdated"
      | "EmergencyWithdraw"
      | "OwnershipTransferred"
      | "Paused"
      | "RewardClaimed"
      | "Staked"
      | "TokenUpdated"
      | "Unpaused"
      | "Unstaked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LOCK_BONUS_180_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_BONUS_30_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_BONUS_365_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_BONUS_90_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_BONUS_NONE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_PERIOD_180_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_PERIOD_30_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_PERIOD_365_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_PERIOD_90_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_PERIOD_NONE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_APY", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_APY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "REWARD_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SECONDS_PER_YEAR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_MIN_BRONZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_MIN_GOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_MIN_PLATINUM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_MIN_SILVER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentAPY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingReward",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakeInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStakers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isStaker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastUpdateTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardPerTokenStored",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAPY",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVibeToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeInfos",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRewardsDistributed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "unstake", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateGlobalRewards",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vibeToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "LOCK_BONUS_180_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_BONUS_30_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_BONUS_365_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_BONUS_90_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_BONUS_NONE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_PERIOD_180_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_PERIOD_30_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_PERIOD_365_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_PERIOD_90_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_PERIOD_NONE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_APY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_APY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SECONDS_PER_YEAR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_MIN_BRONZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_MIN_GOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_MIN_PLATINUM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_MIN_SILVER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addRewards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "currentAPY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStakers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isStaker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastUpdateTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardPerTokenStored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rewards", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAPY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVibeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeInfos", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalRewardsDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateGlobalRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vibeToken", data: BytesLike): Result;
}

export namespace APYUpdatedEvent {
  export type InputTuple = [oldAPY: BigNumberish, newAPY: BigNumberish];
  export type OutputTuple = [oldAPY: bigint, newAPY: bigint];
  export interface OutputObject {
    oldAPY: bigint;
    newAPY: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    tier: BigNumberish,
    lockPeriod: BigNumberish,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    tier: bigint,
    lockPeriod: bigint,
    unlockTime: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    tier: bigint;
    lockPeriod: bigint;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenUpdatedEvent {
  export type InputTuple = [oldToken: AddressLike, newToken: AddressLike];
  export type OutputTuple = [oldToken: string, newToken: string];
  export interface OutputObject {
    oldToken: string;
    newToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VIBStaking extends BaseContract {
  connect(runner?: ContractRunner | null): VIBStaking;
  waitForDeployment(): Promise<this>;

  interface: VIBStakingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LOCK_BONUS_180_DAYS: TypedContractMethod<[], [bigint], "view">;

  LOCK_BONUS_30_DAYS: TypedContractMethod<[], [bigint], "view">;

  LOCK_BONUS_365_DAYS: TypedContractMethod<[], [bigint], "view">;

  LOCK_BONUS_90_DAYS: TypedContractMethod<[], [bigint], "view">;

  LOCK_BONUS_NONE: TypedContractMethod<[], [bigint], "view">;

  LOCK_PERIOD_180_DAYS: TypedContractMethod<[], [bigint], "view">;

  LOCK_PERIOD_30_DAYS: TypedContractMethod<[], [bigint], "view">;

  LOCK_PERIOD_365_DAYS: TypedContractMethod<[], [bigint], "view">;

  LOCK_PERIOD_90_DAYS: TypedContractMethod<[], [bigint], "view">;

  LOCK_PERIOD_NONE: TypedContractMethod<[], [bigint], "view">;

  MAX_APY: TypedContractMethod<[], [bigint], "view">;

  MIN_APY: TypedContractMethod<[], [bigint], "view">;

  REWARD_PRECISION: TypedContractMethod<[], [bigint], "view">;

  SECONDS_PER_YEAR: TypedContractMethod<[], [bigint], "view">;

  TIER_MIN_BRONZE: TypedContractMethod<[], [bigint], "view">;

  TIER_MIN_GOLD: TypedContractMethod<[], [bigint], "view">;

  TIER_MIN_PLATINUM: TypedContractMethod<[], [bigint], "view">;

  TIER_MIN_SILVER: TypedContractMethod<[], [bigint], "view">;

  addRewards: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  calculateTier: TypedContractMethod<[amount: BigNumberish], [bigint], "view">;

  claimReward: TypedContractMethod<[], [void], "nonpayable">;

  currentAPY: TypedContractMethod<[], [bigint], "view">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  getPendingReward: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getStakeInfo: TypedContractMethod<
    [user: AddressLike],
    [VIBStaking.StakeInfoStructOutput],
    "view"
  >;

  getStakerCount: TypedContractMethod<[], [bigint], "view">;

  getStakers: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  getUserTier: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  isStaker: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lastUpdateTime: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardPerTokenStored: TypedContractMethod<[], [bigint], "view">;

  rewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setAPY: TypedContractMethod<[newAPY: BigNumberish], [void], "nonpayable">;

  setVibeToken: TypedContractMethod<
    [_vibeToken: AddressLike],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<
    [amount: BigNumberish, lockPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakeInfos: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        amount: bigint;
        tier: bigint;
        lockPeriod: bigint;
        stakeTime: bigint;
        unlockTime: bigint;
        rewardPerTokenPaid: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  stakers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  totalRewardsDistributed: TypedContractMethod<[], [bigint], "view">;

  totalStaked: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  unstake: TypedContractMethod<[], [void], "nonpayable">;

  updateGlobalRewards: TypedContractMethod<[], [void], "nonpayable">;

  vibeToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LOCK_BONUS_180_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_BONUS_30_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_BONUS_365_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_BONUS_90_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_BONUS_NONE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_PERIOD_180_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_PERIOD_30_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_PERIOD_365_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_PERIOD_90_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_PERIOD_NONE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_APY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_APY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REWARD_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SECONDS_PER_YEAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_MIN_BRONZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_MIN_GOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_MIN_PLATINUM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_MIN_SILVER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addRewards"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateTier"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentAPY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPendingReward"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStakeInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [VIBStaking.StakeInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStakerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStakers"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTier"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isStaker"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastUpdateTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardPerTokenStored"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAPY"
  ): TypedContractMethod<[newAPY: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVibeToken"
  ): TypedContractMethod<[_vibeToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [amount: BigNumberish, lockPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakeInfos"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        amount: bigint;
        tier: bigint;
        lockPeriod: bigint;
        stakeTime: bigint;
        unlockTime: bigint;
        rewardPerTokenPaid: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalRewardsDistributed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateGlobalRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vibeToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "APYUpdated"
  ): TypedContractEvent<
    APYUpdatedEvent.InputTuple,
    APYUpdatedEvent.OutputTuple,
    APYUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "TokenUpdated"
  ): TypedContractEvent<
    TokenUpdatedEvent.InputTuple,
    TokenUpdatedEvent.OutputTuple,
    TokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;

  filters: {
    "APYUpdated(uint256,uint256)": TypedContractEvent<
      APYUpdatedEvent.InputTuple,
      APYUpdatedEvent.OutputTuple,
      APYUpdatedEvent.OutputObject
    >;
    APYUpdated: TypedContractEvent<
      APYUpdatedEvent.InputTuple,
      APYUpdatedEvent.OutputTuple,
      APYUpdatedEvent.OutputObject
    >;

    "EmergencyWithdraw(address,uint256)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RewardClaimed(address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "Staked(address,uint256,uint8,uint8,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "TokenUpdated(address,address)": TypedContractEvent<
      TokenUpdatedEvent.InputTuple,
      TokenUpdatedEvent.OutputTuple,
      TokenUpdatedEvent.OutputObject
    >;
    TokenUpdated: TypedContractEvent<
      TokenUpdatedEvent.InputTuple,
      TokenUpdatedEvent.OutputTuple,
      TokenUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Unstaked(address,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
  };
}
