/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace VIBVesting {
  export type BeneficiaryInfoStruct = {
    totalAmount: BigNumberish;
    releasedAmount: BigNumberish;
    vestingStart: BigNumberish;
    vestingDuration: BigNumberish;
    cliffPeriod: BigNumberish;
    vestingType: BigNumberish;
    isActive: boolean;
  };

  export type BeneficiaryInfoStructOutput = [
    totalAmount: bigint,
    releasedAmount: bigint,
    vestingStart: bigint,
    vestingDuration: bigint,
    cliffPeriod: bigint,
    vestingType: bigint,
    isActive: boolean
  ] & {
    totalAmount: bigint;
    releasedAmount: bigint;
    vestingStart: bigint;
    vestingDuration: bigint;
    cliffPeriod: bigint;
    vestingType: bigint;
    isActive: boolean;
  };
}

export interface VIBVestingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PRECISION"
      | "SECONDS_PER_YEAR"
      | "addBeneficiary"
      | "addEarlySupporters"
      | "addTeamMembers"
      | "beneficiaries"
      | "beneficiaryCount"
      | "beneficiaryList"
      | "contractBalance"
      | "emergencyWithdraw"
      | "getBeneficiaries"
      | "getBeneficiaryInfo"
      | "getReleasableAmount"
      | "getVestedAmount"
      | "isBeneficiary"
      | "owner"
      | "release"
      | "removeBeneficiary"
      | "renounceOwnership"
      | "setVibeToken"
      | "totalReleased"
      | "transferOwnership"
      | "vibeToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BeneficiaryAdded"
      | "BeneficiaryRemoved"
      | "EmergencyWithdraw"
      | "OwnershipTransferred"
      | "TokenUpdated"
      | "TokensReleased"
  ): EventFragment;

  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SECONDS_PER_YEAR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addBeneficiary",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addEarlySupporters",
    values: [AddressLike[], BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addTeamMembers",
    values: [AddressLike[], BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "beneficiaries",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beneficiaryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "beneficiaryList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiaries",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiaryInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReleasableAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVestedAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBeneficiary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "release", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeBeneficiary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setVibeToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalReleased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vibeToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SECONDS_PER_YEAR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addEarlySupporters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addTeamMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beneficiaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beneficiaryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beneficiaryList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiaryInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReleasableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVibeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReleased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vibeToken", data: BytesLike): Result;
}

export namespace BeneficiaryAddedEvent {
  export type InputTuple = [
    beneficiary: AddressLike,
    amount: BigNumberish,
    beneficiaryType: BigNumberish,
    vestingStart: BigNumberish,
    vestingDuration: BigNumberish,
    cliffPeriod: BigNumberish
  ];
  export type OutputTuple = [
    beneficiary: string,
    amount: bigint,
    beneficiaryType: bigint,
    vestingStart: bigint,
    vestingDuration: bigint,
    cliffPeriod: bigint
  ];
  export interface OutputObject {
    beneficiary: string;
    amount: bigint;
    beneficiaryType: bigint;
    vestingStart: bigint;
    vestingDuration: bigint;
    cliffPeriod: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeneficiaryRemovedEvent {
  export type InputTuple = [
    beneficiary: AddressLike,
    remainingAmount: BigNumberish
  ];
  export type OutputTuple = [beneficiary: string, remainingAmount: bigint];
  export interface OutputObject {
    beneficiary: string;
    remainingAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenUpdatedEvent {
  export type InputTuple = [oldToken: AddressLike, newToken: AddressLike];
  export type OutputTuple = [oldToken: string, newToken: string];
  export interface OutputObject {
    oldToken: string;
    newToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensReleasedEvent {
  export type InputTuple = [beneficiary: AddressLike, amount: BigNumberish];
  export type OutputTuple = [beneficiary: string, amount: bigint];
  export interface OutputObject {
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VIBVesting extends BaseContract {
  connect(runner?: ContractRunner | null): VIBVesting;
  waitForDeployment(): Promise<this>;

  interface: VIBVestingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PRECISION: TypedContractMethod<[], [bigint], "view">;

  SECONDS_PER_YEAR: TypedContractMethod<[], [bigint], "view">;

  addBeneficiary: TypedContractMethod<
    [
      beneficiary: AddressLike,
      amount: BigNumberish,
      beneficiaryType: BigNumberish,
      vestingStart: BigNumberish,
      vestingDuration: BigNumberish,
      cliffPeriod: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  addEarlySupporters: TypedContractMethod<
    [
      supporters: AddressLike[],
      amounts: BigNumberish[],
      vestingStart: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  addTeamMembers: TypedContractMethod<
    [
      teamMembers: AddressLike[],
      amounts: BigNumberish[],
      vestingStart: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  beneficiaries: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        totalAmount: bigint;
        releasedAmount: bigint;
        vestingStart: bigint;
        vestingDuration: bigint;
        cliffPeriod: bigint;
        vestingType: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  beneficiaryCount: TypedContractMethod<[], [bigint], "view">;

  beneficiaryList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  contractBalance: TypedContractMethod<[], [bigint], "view">;

  emergencyWithdraw: TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  getBeneficiaries: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  getBeneficiaryInfo: TypedContractMethod<
    [beneficiary: AddressLike],
    [VIBVesting.BeneficiaryInfoStructOutput],
    "view"
  >;

  getReleasableAmount: TypedContractMethod<
    [beneficiary: AddressLike],
    [bigint],
    "view"
  >;

  getVestedAmount: TypedContractMethod<
    [beneficiary: AddressLike],
    [bigint],
    "view"
  >;

  isBeneficiary: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  release: TypedContractMethod<[], [void], "nonpayable">;

  removeBeneficiary: TypedContractMethod<
    [beneficiary: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setVibeToken: TypedContractMethod<
    [_vibeToken: AddressLike],
    [void],
    "nonpayable"
  >;

  totalReleased: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vibeToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SECONDS_PER_YEAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addBeneficiary"
  ): TypedContractMethod<
    [
      beneficiary: AddressLike,
      amount: BigNumberish,
      beneficiaryType: BigNumberish,
      vestingStart: BigNumberish,
      vestingDuration: BigNumberish,
      cliffPeriod: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addEarlySupporters"
  ): TypedContractMethod<
    [
      supporters: AddressLike[],
      amounts: BigNumberish[],
      vestingStart: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addTeamMembers"
  ): TypedContractMethod<
    [
      teamMembers: AddressLike[],
      amounts: BigNumberish[],
      vestingStart: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beneficiaries"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        totalAmount: bigint;
        releasedAmount: bigint;
        vestingStart: bigint;
        vestingDuration: bigint;
        cliffPeriod: bigint;
        vestingType: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "beneficiaryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "beneficiaryList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "contractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBeneficiaries"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBeneficiaryInfo"
  ): TypedContractMethod<
    [beneficiary: AddressLike],
    [VIBVesting.BeneficiaryInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReleasableAmount"
  ): TypedContractMethod<[beneficiary: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVestedAmount"
  ): TypedContractMethod<[beneficiary: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isBeneficiary"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeBeneficiary"
  ): TypedContractMethod<[beneficiary: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVibeToken"
  ): TypedContractMethod<[_vibeToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalReleased"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vibeToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BeneficiaryAdded"
  ): TypedContractEvent<
    BeneficiaryAddedEvent.InputTuple,
    BeneficiaryAddedEvent.OutputTuple,
    BeneficiaryAddedEvent.OutputObject
  >;
  getEvent(
    key: "BeneficiaryRemoved"
  ): TypedContractEvent<
    BeneficiaryRemovedEvent.InputTuple,
    BeneficiaryRemovedEvent.OutputTuple,
    BeneficiaryRemovedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenUpdated"
  ): TypedContractEvent<
    TokenUpdatedEvent.InputTuple,
    TokenUpdatedEvent.OutputTuple,
    TokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokensReleased"
  ): TypedContractEvent<
    TokensReleasedEvent.InputTuple,
    TokensReleasedEvent.OutputTuple,
    TokensReleasedEvent.OutputObject
  >;

  filters: {
    "BeneficiaryAdded(address,uint256,uint8,uint256,uint256,uint256)": TypedContractEvent<
      BeneficiaryAddedEvent.InputTuple,
      BeneficiaryAddedEvent.OutputTuple,
      BeneficiaryAddedEvent.OutputObject
    >;
    BeneficiaryAdded: TypedContractEvent<
      BeneficiaryAddedEvent.InputTuple,
      BeneficiaryAddedEvent.OutputTuple,
      BeneficiaryAddedEvent.OutputObject
    >;

    "BeneficiaryRemoved(address,uint256)": TypedContractEvent<
      BeneficiaryRemovedEvent.InputTuple,
      BeneficiaryRemovedEvent.OutputTuple,
      BeneficiaryRemovedEvent.OutputObject
    >;
    BeneficiaryRemoved: TypedContractEvent<
      BeneficiaryRemovedEvent.InputTuple,
      BeneficiaryRemovedEvent.OutputTuple,
      BeneficiaryRemovedEvent.OutputObject
    >;

    "EmergencyWithdraw(address,uint256)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenUpdated(address,address)": TypedContractEvent<
      TokenUpdatedEvent.InputTuple,
      TokenUpdatedEvent.OutputTuple,
      TokenUpdatedEvent.OutputObject
    >;
    TokenUpdated: TypedContractEvent<
      TokenUpdatedEvent.InputTuple,
      TokenUpdatedEvent.OutputTuple,
      TokenUpdatedEvent.OutputObject
    >;

    "TokensReleased(address,uint256)": TypedContractEvent<
      TokensReleasedEvent.InputTuple,
      TokensReleasedEvent.OutputTuple,
      TokensReleasedEvent.OutputObject
    >;
    TokensReleased: TypedContractEvent<
      TokensReleasedEvent.InputTuple,
      TokensReleasedEvent.OutputTuple,
      TokensReleasedEvent.OutputObject
    >;
  };
}
