/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ZKCredential {
  export type CredentialStruct = {
    credentialId: BytesLike;
    holder: AddressLike;
    credType: BigNumberish;
    validFrom: BigNumberish;
    validUntil: BigNumberish;
    commitment: BytesLike;
    nullifier: BytesLike;
    status: BigNumberish;
    score: BigNumberish;
  };

  export type CredentialStructOutput = [
    credentialId: string,
    holder: string,
    credType: bigint,
    validFrom: bigint,
    validUntil: bigint,
    commitment: string,
    nullifier: string,
    status: bigint,
    score: bigint
  ] & {
    credentialId: string;
    holder: string;
    credType: bigint;
    validFrom: bigint;
    validUntil: bigint;
    commitment: string;
    nullifier: string;
    status: bigint;
    score: bigint;
  };

  export type VerificationKeyStruct = {
    alpha: [BigNumberish, BigNumberish];
    beta: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    gamma: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    delta: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
  };

  export type VerificationKeyStructOutput = [
    alpha: [bigint, bigint],
    beta: [[bigint, bigint], [bigint, bigint]],
    gamma: [[bigint, bigint], [bigint, bigint]],
    delta: [[bigint, bigint], [bigint, bigint]]
  ] & {
    alpha: [bigint, bigint];
    beta: [[bigint, bigint], [bigint, bigint]];
    gamma: [[bigint, bigint], [bigint, bigint]];
    delta: [[bigint, bigint], [bigint, bigint]];
  };

  export type ProofDataStruct = {
    a: [BigNumberish, BigNumberish];
    b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    c: [BigNumberish, BigNumberish];
    publicInputs: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
  };

  export type ProofDataStructOutput = [
    a: [bigint, bigint],
    b: [[bigint, bigint], [bigint, bigint]],
    c: [bigint, bigint],
    publicInputs: [bigint, bigint, bigint, bigint]
  ] & {
    a: [bigint, bigint];
    b: [[bigint, bigint], [bigint, bigint]];
    c: [bigint, bigint];
    publicInputs: [bigint, bigint, bigint, bigint];
  };
}

export interface ZKCredentialInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_CREDENTIAL_DURATION"
      | "MIN_CREDENTIAL_DURATION"
      | "allCredentials"
      | "authorizeVerifier"
      | "authorizedVerifiers"
      | "credentialCounts"
      | "credentials"
      | "getCredential"
      | "getCredentialCount"
      | "getCredentialCountByType"
      | "getHolderCredentials"
      | "getHolderCredentialsByType"
      | "getStats"
      | "getVerificationKey"
      | "hasCredentialType"
      | "holderCredentials"
      | "isCredentialValid"
      | "issuer"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "revokeCredential"
      | "revokeVerifier"
      | "setIssuer"
      | "transferOwnership"
      | "unpause"
      | "updateVerificationKey"
      | "usedNullifiers"
      | "verifyAndIssue"
      | "verifyCredential"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialIssued"
      | "CredentialRevoked"
      | "CredentialVerified"
      | "IssuerUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
      | "VerificationKeyUpdated"
      | "VerifierAuthorized"
      | "VerifierRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_CREDENTIAL_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_CREDENTIAL_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allCredentials",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedVerifiers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "credentialCounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "credentials",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredential",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredentialCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCredentialCountByType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHolderCredentials",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHolderCredentialsByType",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getVerificationKey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCredentialType",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "holderCredentials",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isCredentialValid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "issuer", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateVerificationKey",
    values: [
      BigNumberish,
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "usedNullifiers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndIssue",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike,
      ZKCredential.ProofDataStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCredential",
    values: [BytesLike, BytesLike, ZKCredential.ProofDataStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_CREDENTIAL_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_CREDENTIAL_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentialCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredentialCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredentialCountByType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHolderCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHolderCredentialsByType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasCredentialType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "holderCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCredentialValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issuer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setIssuer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateVerificationKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedNullifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndIssue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCredential",
    data: BytesLike
  ): Result;
}

export namespace CredentialIssuedEvent {
  export type InputTuple = [
    credentialId: BytesLike,
    holder: AddressLike,
    credType: BigNumberish,
    validUntil: BigNumberish
  ];
  export type OutputTuple = [
    credentialId: string,
    holder: string,
    credType: bigint,
    validUntil: bigint
  ];
  export interface OutputObject {
    credentialId: string;
    holder: string;
    credType: bigint;
    validUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [credentialId: BytesLike, reason: string];
  export type OutputTuple = [credentialId: string, reason: string];
  export interface OutputObject {
    credentialId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialVerifiedEvent {
  export type InputTuple = [
    credentialId: BytesLike,
    verifier: AddressLike,
    isValid: boolean
  ];
  export type OutputTuple = [
    credentialId: string,
    verifier: string,
    isValid: boolean
  ];
  export interface OutputObject {
    credentialId: string;
    verifier: string;
    isValid: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerUpdatedEvent {
  export type InputTuple = [oldIssuer: AddressLike, newIssuer: AddressLike];
  export type OutputTuple = [oldIssuer: string, newIssuer: string];
  export interface OutputObject {
    oldIssuer: string;
    newIssuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationKeyUpdatedEvent {
  export type InputTuple = [credType: BigNumberish];
  export type OutputTuple = [credType: bigint];
  export interface OutputObject {
    credType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierAuthorizedEvent {
  export type InputTuple = [verifier: AddressLike];
  export type OutputTuple = [verifier: string];
  export interface OutputObject {
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierRevokedEvent {
  export type InputTuple = [verifier: AddressLike];
  export type OutputTuple = [verifier: string];
  export interface OutputObject {
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ZKCredential extends BaseContract {
  connect(runner?: ContractRunner | null): ZKCredential;
  waitForDeployment(): Promise<this>;

  interface: ZKCredentialInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_CREDENTIAL_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_CREDENTIAL_DURATION: TypedContractMethod<[], [bigint], "view">;

  allCredentials: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  authorizeVerifier: TypedContractMethod<
    [verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedVerifiers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  credentialCounts: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  credentials: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint
      ] & {
        credentialId: string;
        holder: string;
        credType: bigint;
        validFrom: bigint;
        validUntil: bigint;
        commitment: string;
        nullifier: string;
        status: bigint;
        score: bigint;
      }
    ],
    "view"
  >;

  getCredential: TypedContractMethod<
    [credentialId: BytesLike],
    [ZKCredential.CredentialStructOutput],
    "view"
  >;

  getCredentialCount: TypedContractMethod<[], [bigint], "view">;

  getCredentialCountByType: TypedContractMethod<
    [credType: BigNumberish],
    [bigint],
    "view"
  >;

  getHolderCredentials: TypedContractMethod<
    [holder: AddressLike],
    [string[]],
    "view"
  >;

  getHolderCredentialsByType: TypedContractMethod<
    [holder: AddressLike, credType: BigNumberish],
    [string[]],
    "view"
  >;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalCredentials: bigint;
        identityCount: bigint;
        serviceProviderCount: bigint;
        governanceCount: bigint;
        premiumCount: bigint;
        trustedNodeCount: bigint;
      }
    ],
    "view"
  >;

  getVerificationKey: TypedContractMethod<
    [credType: BigNumberish],
    [ZKCredential.VerificationKeyStructOutput],
    "view"
  >;

  hasCredentialType: TypedContractMethod<
    [holder: AddressLike, credType: BigNumberish],
    [boolean],
    "view"
  >;

  holderCredentials: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  isCredentialValid: TypedContractMethod<
    [credentialId: BytesLike],
    [boolean],
    "view"
  >;

  issuer: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeCredential: TypedContractMethod<
    [credentialId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  revokeVerifier: TypedContractMethod<
    [verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  setIssuer: TypedContractMethod<[_issuer: AddressLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateVerificationKey: TypedContractMethod<
    [
      credType: BigNumberish,
      alpha: [BigNumberish, BigNumberish],
      beta: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      gamma: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      delta: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]]
    ],
    [void],
    "nonpayable"
  >;

  usedNullifiers: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifyAndIssue: TypedContractMethod<
    [
      credType: BigNumberish,
      validDuration: BigNumberish,
      commitment: BytesLike,
      proof: ZKCredential.ProofDataStruct
    ],
    [string],
    "nonpayable"
  >;

  verifyCredential: TypedContractMethod<
    [
      credentialId: BytesLike,
      nullifier: BytesLike,
      proof: ZKCredential.ProofDataStruct
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_CREDENTIAL_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_CREDENTIAL_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allCredentials"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "authorizeVerifier"
  ): TypedContractMethod<[verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedVerifiers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "credentialCounts"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "credentials"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint
      ] & {
        credentialId: string;
        holder: string;
        credType: bigint;
        validFrom: bigint;
        validUntil: bigint;
        commitment: string;
        nullifier: string;
        status: bigint;
        score: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCredential"
  ): TypedContractMethod<
    [credentialId: BytesLike],
    [ZKCredential.CredentialStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCredentialCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCredentialCountByType"
  ): TypedContractMethod<[credType: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHolderCredentials"
  ): TypedContractMethod<[holder: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getHolderCredentialsByType"
  ): TypedContractMethod<
    [holder: AddressLike, credType: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalCredentials: bigint;
        identityCount: bigint;
        serviceProviderCount: bigint;
        governanceCount: bigint;
        premiumCount: bigint;
        trustedNodeCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVerificationKey"
  ): TypedContractMethod<
    [credType: BigNumberish],
    [ZKCredential.VerificationKeyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasCredentialType"
  ): TypedContractMethod<
    [holder: AddressLike, credType: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "holderCredentials"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCredentialValid"
  ): TypedContractMethod<[credentialId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issuer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<
    [credentialId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeVerifier"
  ): TypedContractMethod<[verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setIssuer"
  ): TypedContractMethod<[_issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateVerificationKey"
  ): TypedContractMethod<
    [
      credType: BigNumberish,
      alpha: [BigNumberish, BigNumberish],
      beta: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      gamma: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      delta: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usedNullifiers"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyAndIssue"
  ): TypedContractMethod<
    [
      credType: BigNumberish,
      validDuration: BigNumberish,
      commitment: BytesLike,
      proof: ZKCredential.ProofDataStruct
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyCredential"
  ): TypedContractMethod<
    [
      credentialId: BytesLike,
      nullifier: BytesLike,
      proof: ZKCredential.ProofDataStruct
    ],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "CredentialIssued"
  ): TypedContractEvent<
    CredentialIssuedEvent.InputTuple,
    CredentialIssuedEvent.OutputTuple,
    CredentialIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialVerified"
  ): TypedContractEvent<
    CredentialVerifiedEvent.InputTuple,
    CredentialVerifiedEvent.OutputTuple,
    CredentialVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerUpdated"
  ): TypedContractEvent<
    IssuerUpdatedEvent.InputTuple,
    IssuerUpdatedEvent.OutputTuple,
    IssuerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationKeyUpdated"
  ): TypedContractEvent<
    VerificationKeyUpdatedEvent.InputTuple,
    VerificationKeyUpdatedEvent.OutputTuple,
    VerificationKeyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierAuthorized"
  ): TypedContractEvent<
    VerifierAuthorizedEvent.InputTuple,
    VerifierAuthorizedEvent.OutputTuple,
    VerifierAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierRevoked"
  ): TypedContractEvent<
    VerifierRevokedEvent.InputTuple,
    VerifierRevokedEvent.OutputTuple,
    VerifierRevokedEvent.OutputObject
  >;

  filters: {
    "CredentialIssued(bytes32,address,uint8,uint256)": TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;
    CredentialIssued: TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;

    "CredentialRevoked(bytes32,string)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "CredentialVerified(bytes32,address,bool)": TypedContractEvent<
      CredentialVerifiedEvent.InputTuple,
      CredentialVerifiedEvent.OutputTuple,
      CredentialVerifiedEvent.OutputObject
    >;
    CredentialVerified: TypedContractEvent<
      CredentialVerifiedEvent.InputTuple,
      CredentialVerifiedEvent.OutputTuple,
      CredentialVerifiedEvent.OutputObject
    >;

    "IssuerUpdated(address,address)": TypedContractEvent<
      IssuerUpdatedEvent.InputTuple,
      IssuerUpdatedEvent.OutputTuple,
      IssuerUpdatedEvent.OutputObject
    >;
    IssuerUpdated: TypedContractEvent<
      IssuerUpdatedEvent.InputTuple,
      IssuerUpdatedEvent.OutputTuple,
      IssuerUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VerificationKeyUpdated(uint8)": TypedContractEvent<
      VerificationKeyUpdatedEvent.InputTuple,
      VerificationKeyUpdatedEvent.OutputTuple,
      VerificationKeyUpdatedEvent.OutputObject
    >;
    VerificationKeyUpdated: TypedContractEvent<
      VerificationKeyUpdatedEvent.InputTuple,
      VerificationKeyUpdatedEvent.OutputTuple,
      VerificationKeyUpdatedEvent.OutputObject
    >;

    "VerifierAuthorized(address)": TypedContractEvent<
      VerifierAuthorizedEvent.InputTuple,
      VerifierAuthorizedEvent.OutputTuple,
      VerifierAuthorizedEvent.OutputObject
    >;
    VerifierAuthorized: TypedContractEvent<
      VerifierAuthorizedEvent.InputTuple,
      VerifierAuthorizedEvent.OutputTuple,
      VerifierAuthorizedEvent.OutputObject
    >;

    "VerifierRevoked(address)": TypedContractEvent<
      VerifierRevokedEvent.InputTuple,
      VerifierRevokedEvent.OutputTuple,
      VerifierRevokedEvent.OutputObject
    >;
    VerifierRevoked: TypedContractEvent<
      VerifierRevokedEvent.InputTuple,
      VerifierRevokedEvent.OutputTuple,
      VerifierRevokedEvent.OutputObject
    >;
  };
}
